using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace BookApiProject.Models
{
    public class JsonObject
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] //id is generated by db not user
        public int Id { get; set; }
        public string JsonString { get; set; }
    }
}
